# Generated by Django 5.1.4 on 2024-12-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='static\\Files')),
                ('filename', models.CharField(max_length=100)),
                ('uploader', models.EmailField(max_length=254)),
                ('rsa_encrypted_key', models.BinaryField()),
                ('private_key', models.BinaryField()),
                ('encrypted_data', models.BinaryField()),
                ('status', models.CharField(default='Encrypted', max_length=100)),
            ],
            options={
                'db_table': 'UploadFile',
            },
        ),
    ]
