# Generated by Django 5.1.4 on 2024-12-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='static/assets\\Files'),
        ),
    ]
