# Generated by Django 5.1.4 on 2024-12-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_uploadfile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester', models.EmailField(max_length=254)),
                ('file', models.FileField(upload_to='static/assets\\RequestedFiles')),
                ('filename', models.CharField(max_length=100)),
                ('uploader', models.EmailField(max_length=254)),
                ('rsa_encrypted_key', models.BinaryField()),
                ('private_key', models.BinaryField()),
                ('encrypted_data', models.BinaryField()),
                ('status', models.CharField(default='Encrypted', max_length=100)),
                ('otp', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'RequestFile',
            },
        ),
    ]
