# Generated by Django 5.1.4 on 2024-12-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_requestfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfile',
            name='fid',
            field=models.IntegerField(null=True),
        ),
    ]
